swiftmailer:
    url: 'smtp.gmail.com'
    transport: gmail
    username: 'exempledemojr@gmail.com'
    password: 'Guild1910a$a'
    port: 465
    encryption: ssl
    auth_mode: login
    spool: { type: 'memory' }
